### ISSUE TITLE
Popup Channel List not work (browser_mod 2)

### ISSUE THREAD

**Issue by rogodra** [madmicio/LG-WebOS-Remote-Control#101]
browser_mod s'ha actualitzat a la versió 2, hi ha diversos canvis, de manera que ha deixat de funcionar el botó de Channel List, és una opció molt usada a casa.

He intentat editar el fitxer per veure si aconseguia que funcionés el botó de Channel List, però els meus coneixements de programació són limitats.

Han canviat la manera d'anomenar el popup, potser d'aquí vingui el problema.

```
browser_mod:
   command: popup
   title: My title
   card:
     type: ...etc...
```
to

```
browser_mod:
   service: browser_mod.popup
   data:
     title: My title
     content:
       type: ...etc...
```

https://github.com/thomasloven/hass-browser_mod/blob/master/documentation/services.md

Gràcies per la feina.
