### ISSUE TITLE
This does not work

### ISSUE THREAD

**Issue by ddjj767** [madmicio/LG-WebOS-Remote-Control#117]
By the looks of the open issues, this plugin doesn't work anymore. I've followed the instructions but nothing changes.

Anyone able to help?

**Comment by star114** [comment]
I'm still using it as expected.
You might get some logs/errors when you follow the instructions to set up.
Without any information like logs, your system, no one can help you..

**Comment by nicknol** [comment]
@ddjj767 I installed it yesterday. and it works for me. No issues so far

**Comment by amorphina** [comment]
@star114 and @nicknol can you guys share some example config.
When I add this to my configuration.yaml 
```yaml
resources:
  - type: module
    url: /config/LG-WebOS-Remote-Control/lg-remote-control.js
```
and click the `check configuration` button through the web UI I get:
```
Configuration warnings
Integration error: resources - Integration 'resources' not found.
```
