### ISSUE TITLE
Add Spotify and Settings buttons, add Apple Music icon

### ISSUE THREAD

**Issue by TRRAXT** [madmicio/LG-WebOS-Remote-Control#144]
```
sources:
- icon: mdi:youtube
  name: YouTube
- icon: mdi:plex
  name: Plex
- icon: mdi:spotify
  name: spotify
- icon: mdi:music
  name: Apple Music
```
I wanna use Spotify, but it's doens't open (but have icon, lol). Apple Music works, but has no icon.
And ofc, how to add settings button? 
This doesn't work:
- icon: mdi:music
  name: Settings
