### ISSUE TITLE
Menu Key

### ISSUE THREAD

**Issue by extremelyonline** [madmicio/LG-WebOS-Remote-Control#153]
In case anyone is looking, here's a way to remap the EXIT key to work as the MENU key

```
keys:
  EXIT:
    service: script.tv_press_menu_button
    data:
      entity_id: media_player.lg_webos_smart_tv

```

And the script:

```
alias: "LG: Press MENU Button"
sequence:
  - action: webostv.button
    metadata: {}
    data:
      entity_id: media_player.lg_webos_smart_tv
      button: MENU
```
