### ISSUE TITLE
Custom source all give an error. 

### ISSUE THREAD

**Issue by vandalon** [madmicio/LG-WebOS-Remote-Control#16]
```
Received invalid webhook payload: required key not provided @ data[12]['state']. Got None
```

config:

```
                sources:
                  - icon: 'mdi:netflix'
                    app: Netflix
                  - icon: 'mdi:amazon'
                    app: Amazon Prime Video
                  - icon: disney
                    app: Disney+
                  - icon: 'mdi:youtube'
                    app: YouTube

```
