### ISSUE TITLE
Running Custom Actions In Sources List

### ISSUE THREAD

**Issue by lou-cucci** [madmicio/LG-WebOS-Remote-Control#163]
Here are my yaml:

```
            type: custom:lg-remote-control
            entity: media_player.lg_webos_tv_oled65g36la
            mac: XX:XX:XX:XX:XX:XX
            is_smart_tv: "true"
            sources:
              - icon: mdi:netflix
                name: netflix
              - icon: si:amazon
                name: **Prime**
```

I have an automation that looks for **Prime** being pressed and then will trigger this automation (it launches Amazon Prime on my Apple TV):

```
- id: lg_amazon_prime
  alias: Start Amazon Prime on Apple TV
  trigger:
    platform: event
    event_type: call_service
    event_data:
      domain: media_player
      service: select_source
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.service_data.entity_id in 
         ['media_player.lg_webos_tv_oled55g36la', 'media_player.lg_webos_tv_oled65g36la','media_player.lg_webos_tv_oled42c44la_2'] and 
         trigger.event.data.service_data.source == '**Prime**' }}
  action:
    - service: media_player.select_source
      data:
        entity_id: >
          {{ trigger.event.data.service_data.entity_id }}
        source: Apple OTT
    - service: media_player.select_source
      data:
        entity_id: >
          {% if trigger.event.data.service_data.entity_id == 'media_player.lg_webos_tv_oled55g36la' %}
            media_player.lou_office
          {% elif trigger.event.data.service_data.entity_id == 'media_player.lg_webos_tv_oled65g36la' %}
            media_player.living_room_2
          {% elif trigger.event.data.service_data.entity_id == 'media_player.lg_webos_tv_oled42c44la_2' %}
            media_player.guest_room            
          {% endif %}
        source: Prime Video

```

Ir works fine but generates the error

![Image](https://github.com/user-attachments/assets/33f69f6a-db3f-4034-9e49-37dece47f9a3)

Is there anyway to have 'sources'->'name:' that launch an automation and not create errors like my work around above?

Thanks

Lou
