### ISSUE TITLE
Configure channel pad and channel number

### ISSUE THREAD

**Issue by phcella** [madmicio/LG-WebOS-Remote-Control#30]
Here in Brazil, we have DTV (digital tv) and it has some channels in one channel number as you can see on the image below 

![image](https://user-images.githubusercontent.com/20034679/90560338-51eaff80-e175-11ea-829c-45691c936df3.png)

I would like to know how I need to write the channel number on the configuration.

And another problem, after I click on the Channel Logo, appeared an error: "Failed to call the service media_player/play_media.'NoneType' object is not iterable". You can see the screenshot below

![image](https://user-images.githubusercontent.com/20034679/90560653-d0e03800-e175-11ea-9558-ccf7ba346fa6.png)

**Comment by ghostrobo282** [comment]
same problem mine doesnt even show the icons but has a button what is the file fomat that it needs

**Comment by jjmuriel** [comment]
Same problem here, the logo is showing fin3:

```

type: custom:lg-remote-control
entity: media_player.tv_salacomedor
sources:
  - icon: mdi:netflix
    name: Netflix
  - icon: disney
    name: Disney
  - icon: mdi:youtube
    name: YouTube
  - icon: mdi:amazon
    name: Amazon Prime Video
  - name: HDMI 1
    icon: mdi:video-input-hdmi
  - name: HDMI 2
    icon: mdi:video-input-hdmi
  - name: HDMI 3
    icon: mdi:video-input-hdmi
  - name: HDMI 4
    icon: mdi:video-input-hdmi
colors:
  texts: blue
  background: blue
  buttons: lightblue
channels:
  - image: /local/images/tv_logo/Star_Channel.png
    number: '312'

```

![image](https://user-images.githubusercontent.com/17131600/125834799-938e7ea5-d1df-43f3-9c85-a3fb4d83e903.png)
