### ISSUE TITLE
undefined header in channel selection window

### ISSUE THREAD

**Issue by Murder3D** [madmicio/LG-WebOS-Remote-Control#33]
Hi everyone, I've setup the **LG TV WebOS Remote Control** via **HACS** with all the components needed following the instructions provided and it works very well.

However, I have a problem with the **channel selection button** that started displaying an **"undefined"** header today.

![undefined](https://user-images.githubusercontent.com/68924586/97143902-d3f23880-1763-11eb-99d4-db78ec1e1d0a.PNG)

I am on HA Core v0.115.6 and OS v4.13

I am using LG WebOS Remote Control, LG WebOS Keypad, LG WebOS channel pad and browser_mod all updated to the latest release.

This is my LG WebOS Remote config in lovelace:

```
channels:
  - image: /local/lg_remote/tv_logo/Rai 1 HD.png
    number: '501'
  - image: /local/lg_remote/tv_logo/Rai 2 HD.png
    number: '502'
  - image: /local/lg_remote/tv_logo/Rai 3 HD.png
    number: '503'
  - image: /local/lg_remote/tv_logo/Rete4 HD.png
    number: '504'
  - image: /local/lg_remote/tv_logo/Canale5 HD.png
    number: '505'
  - image: /local/lg_remote/tv_logo/Italia1 HD.png
    number: '506'
  - image: /local/lg_remote/tv_logo/LA7 HD.png
    number: '507'
  - image: /local/lg_remote/tv_logo/rainews24.png
    number: '48'
  - image: /local/lg_remote/tv_logo/Sky TG24 HD.png
    number: '50'
  - image: /local/lg_remote/tv_logo/TGCOM24.png
    number: '51'
  - image: /local/lg_remote/tv_logo/DMAX.png
    number: '52'
  - image: /local/lg_remote/tv_logo/HGTV.png
    number: '56'
  - image: /local/lg_remote/tv_logo/MotorTrend.png
    number: '59'
colors:
  background: 'rgba(0, 0, 0, 0.5)'
  border: grey
  buttons: 'rgba(0, 0, 0, 0.85)'
  texts: white
dimensions:
  border_width: 3px
  scale: 1
entity: media_player.lg_tv
sources:
  - icon: 'mdi:netflix'
    name: Netflix
  - icon: 'mdi:amazon'
    name: Amazon Prime Video
  - icon: 'mdi:plex'
    name: Plex
  - icon: 'mdi:youtube-tv'
    name: YouTube
  - icon: 'mdi:sony-playstation'
    name: PS4 Pro
  - icon: 'mdi:spotify'
    name: Spotify - Musica e podcast
  - icon: 'mdi:google-chrome'
    name: Browser Web
  - icon: 'mdi:television-classic'
    name: Canali TV
type: 'custom:lg-remote-control'
```

I've tested this on Chrome  (PC) as well as on HA iOS App, Edge and Fully Kyosk Browser and I have the same issue.

The channel selection works fine, it just bother me that the "undefined" header is displayed.

Any suggestions on how to resolve this?

Thank-you
