### ISSUE TITLE
Add hdmi input number on hdmi icon 

### ISSUE THREAD

**Issue by Nik18111997** [madmicio/LG-WebOS-Remote-Control#54]
Can You Add a number in hdmi icon for Identify hdmi source number

Like this
![images__01](https://user-images.githubusercontent.com/81594558/114542548-5ca05a80-9c58-11eb-9595-eaf50c0247b4.png)

**Comment by typxxi** [comment]
Most likely not cause if you look into the configuration of such cards you will find something like this

```
sources:
  - name: YouTube
    icon: 'mdi:youtube-tv'
  - name: HDMI 1
    icon: 'mdi:video-input-hdmi'
  - name: HDMI 2
    icon: 'mdi:video-input-hdmi'
  - name: HDMI 3
    icon: 'mdi:video-input-hdmi'
    friendly_name: KODI

```
And there you can see the icon source which is 'mdi:video-input-hdmi'
The mdi font libary offers for "hdmi" just 1 particular icon based on a search for hdmi but you might convince them to add hdmi_1 ... hdmi_5 

But I guess that will never happen cause if the would suffer from more hdmi till you end at 10 maybe ... 

If you really need that you simply have to do it on your own with a different style 
instead of 3 hdmi icons you can use 
first the "hdmi" icon and then
you use a number "2" icon and number "3" icon ... 

Open the mdi font overview here 
https://pictogrammers.github.io/@mdi/font/5.5.55/

Press ctrl + f and type 'hdmi' to get the only icon that is available

**ATTENTION:** if you simply click on your desired icon to copy and paste it into your card code then that will **not work** !

HA needs this **mdi:video-input-hdmi**
but mdi delivers that **mdi-video-input-hdmi**
so you have always to replace 'mdi-' by 'mdi:'

Do not a plain find and replace of '-' cause they use the '-" quite often.

How to get the 2 and 3 ? 
If you search for number youl will get just 2 results

Here is an example of icon and number you can use even for "hdmi 1 to hmdi 3" as "replacements" cause the look like an ARROW 1 .... 3 and can be seen as "Input 1 to 3"

but they are designed or meant as floors
mdi:home-floor-1
mdi:home-floor-2
mdi:home-floor-3

Here is a screenshot of my use case with hmdi and 2nd and 3rd as input arrows with the 2 and 3
![ScreenShot - 2021-07-07 (3)](https://user-images.githubusercontent.com/20662430/124740927-84335600-df1b-11eb-9cb9-d952de10f621.jpg)
