### ISSUE TITLE
LG Channel Pad not workin

### ISSUE THREAD

**Issue by aymanokail** [madmicio/LG-WebOS-Remote-Control#63]
i have installed the  LG webos remote control + channel pad + browser mode
and the remote is working fine except the channel pad
i have added the channels part in my lovelace card as shown below but nothing happens when i press the channel pad icon 
thank you

```yml
card:
  type: vertical-stack
  cards:
    - type: custom:lg-remote-control
      entity: media_player.lg_tv
      colors:
        texts: black
        background: grey
        border: black
      dimensions:
        scale: 0.9
        border_width: 0px
      sources:
        - icon: mdi:netflix
          name: Netflix
        - icon: mdi:youtube
          name: YouTube
        - icon: mdi:television-classic
          name: Live TV
        - icon: mdi:image-multiple-outline
          name: Photo & Video
      channels:
        - image: /local/lg/IMG_0820.png
          number: '501'
        - image: /local/www/lg/IMG_0821.png
          number: '328'

```
