### ISSUE TITLE
3 dots button

### ISSUE THREAD

**Issue by blaktro** [madmicio/LG-WebOS-Remote-Control#74]
Is it possible to send command for that '3 dots' button on lg magic remote?

**Comment by Xinne** [comment]
Hi, i've created a pull request (#82) to add extra custom buttons. i've discovered that the three dots button uses the SCREEN_REMOTE command, so if you patch your installation (or wait for @madmicio to merge the pull request) you can do:

```yaml
custom_buttons:
  - name: SCREEN_REMOTE
    icon: mdi:dots-horizontal
```
